### ISSUE TITLE
Error while Download action repository 'r0adkll/sign-android-release@v1' in github action workflow.

### ISSUE THREAD

**Issue by amaljofy** [r0adkll/sign-android-release#30]
<img width="1062" alt="Screenshot 2020-11-14 at 11 40 31 AM" src="https://user-images.githubusercontent.com/11680624/99141155-55a3fa80-266e-11eb-9e3e-ae639394ef33.png">

Error: Could not find file '/home/runner/work/_actions/_temp_5b032fb8-b584-4bbb-acfb-d0d02db41d70/_staging/r0adkll-sign-android-release-6079bfc/node_modules/cross-spawn/node_modules/.bin/node-which'

**Comment by glongchi** [comment]
I am having the same issue as well. thanks

**Comment by davwheat** [comment]
Yep, something seems to have broken this in v1.0.3.

**Comment by sainAk** [comment]
This [this link](https://github.com/r0adkll/sign-android-release/blob/master/node_modules/cross-spawn/node_modules/.bin/node-which) points to `node-which` in [this folder](https://github.com/r0adkll/sign-android-release/tree/master/node_modules/which/bin)  where only `which` is present

**Comment by omeryounus** [comment]
Yeah same here, I got the same errorr. Is there any fix for this?

**Comment by r0adkll** [comment]
Uh oh. Okay let me check this out.

**Comment by r0adkll** [comment]
@amaljofy I just pushed `v1.0.4` (and updated `v1`) that should hopefully fix this issue.

**Comment by omeryounus** [comment]
@r0adkll thanks, Can I give it a try now?

**Comment by r0adkll** [comment]
@omeryounus yup! It should be available now

**Comment by omeryounus** [comment]
@r0adkll Awesome! Thankyou!

**Comment by davwheat** [comment]
Works perfectly!

**Comment by omeryounus** [comment]
@davwheat were you able to deploy it? did you use .APK or aab? or both

**Comment by davwheat** [comment]
@omeryounus I have 2 workflows, one for apk and one for aab.

Both completed with no issues for me.

**Comment by qbalsdon** [comment]
I used an AAB - works great! Just release my first Wear OS aab! Whoop whoop!

**Comment by r0adkll** [comment]
Excellent! I'm gonna go ahead and close this issue

**Comment by foliolo** [comment]
Why didn't you update the version to v2 or similar? If you always update the v1 you will make all the builds fails when it is suppose to be stable, don't you think?
Any way, thanks so much for the quick fix!
Great job! 👏

**Comment by amaljofy** [comment]
@r0adkll Great Job! Thank you so much.

**Comment by r0adkll** [comment]
@foliolo I was more or less following this guide for tagging: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#using-tags-for-release-management. Where I just incremented these changes as a minor change (i.e. 1.0.**3** and 1.0.**4**) and updated the accompanying major release tag `v1` to point to those latest changes. The problem here is that I didn't properly test those changes and for that I apologise. 

I would recommend for anyone looking to keep their workflows stable to refer to the release tag directly (which again was my fault in the past for not keeping up with these individual version tags and just updating the major tag)

Cheers!
